# Generated by Django 2.2.2 on 2020-06-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models
import employee.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10, validators=[employee.validators.validate_number])),
                ('email', models.EmailField(max_length=254)),
                ('skills', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10, validators=[employee.validators.validate_skills])),
                ('total_exp', models.IntegerField(blank=True, null=True)),
                ('rel_exp', models.IntegerField(blank=True, null=True)),
                ('cctc', models.IntegerField(blank=True, null=True)),
                ('ectc', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('reason_for_shifting', models.TextField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=30, null=True)),
                ('current_company', models.CharField(blank=True, max_length=30, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('interview_status', models.CharField(blank=True, choices=[('1', 'Round 1 done'), ('2', 'Round 2 done'), ('3', 'HR Round done'), ('4', 'All of the above done'), ('5', 'None done')], default='1', max_length=30, null=True)),
                ('round1_schedule', models.DateTimeField(blank=True, null=True)),
                ('round1_feedback', models.TextField(blank=True, null=True)),
                ('round2_schedule', models.DateTimeField(blank=True, null=True)),
                ('round2_feedback', models.TextField(blank=True, null=True)),
                ('mode_of_interview', models.CharField(choices=[('1', 'Online'), ('2', 'Offline')], default='1', max_length=30)),
                ('sourced_from', models.CharField(blank=True, max_length=30, null=True)),
                ('placement_location', models.CharField(blank=True, max_length=30, null=True)),
                ('hr_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
