# Generated by Django 2.2.2 on 2020-06-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('employee', '0003_auto_20200622_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
